#
# Grus
# Copyright (C) 2001-2020 NationalChip Co., Ltd
# ALL RIGHTS RESERVED!
#
# Makefile: 
#
#=================================================================================#

ifeq ($(CONFIG_LVP_LM_QCY_HEADSET_V0DOT0DOT2_2021_0222), y)

LM_MODEL_DIR_PRE  = lvp/vui/kws/lm_models/enable_lm/qcy_headset/v0.0.2/

INCLUDE_DIR    += $(LM_MODEL_DIR_PRE)/

kws_objs       += $(LM_MODEL_DIR_PRE)/lm_decoder.o
endif
