#
# Grus
# Copyright (C) 2001-2022 NationalChip Co., Ltd
# ALL RIGHTS RESERVED!
#
# Makefile: 
#
#=================================================================================#

ifeq ($(CONFIG_LVP_LM_DRYING_RACK_DEMO_V0DOT0DOT3_2022_0401), y)

LM_MODEL_DIR_PRE  = lvp/vui/kws/lm_models/enable_lm/drying_rack_demo/v0.0.3

INCLUDE_DIR    += $(LM_MODEL_DIR_PRE)/

kws_objs       += $(LM_MODEL_DIR_PRE)/lm_decoder.o
endif
