#
# Grus
# Copyright (C) 2001-2022 NationalChip Co., Ltd
# ALL RIGHTS RESERVED!
#
# Makefile: 
#
#=================================================================================#

ifeq ($(CONFIG_LVP_LM_TOILET_DEMO_V0DOT0DOT1_2022_0125), y)

LM_MODEL_DIR_PRE  = lvp/vui/kws/lm_models/enable_lm/toilet_demo/v0.0.1

INCLUDE_DIR    += $(LM_MODEL_DIR_PRE)/

kws_objs       += $(LM_MODEL_DIR_PRE)/lm_decoder.o
endif
