#
# Grus
# Copyright (C) 2001-2022 NationalChip Co., Ltd
# ALL RIGHTS RESERVED!
#
# Makefile: 
#
#=================================================================================#

ifeq ($(CONFIG_LVP_LM_KWS_ALI_ITON_CURTAIN_V0DOT1DOT0_2022_0621), y)

LM_MODEL_DIR_PRE  = lvp/vui/kws/lm_models/enable_lm/ali_iton_curtain/v0.0.1

INCLUDE_DIR    += $(LM_MODEL_DIR_PRE)/

kws_objs       += $(LM_MODEL_DIR_PRE)/lm_decoder.o
endif
