#
# Grus
# Copyright (C) 2001-2021 NationalChip Co., Ltd
# ALL RIGHTS RESERVED!
#
# Makefile: 
#
#=================================================================================#

ifeq ($(CONFIG_LVP_LM_MIKE_BATHROOM_HEATER_V0DOT0DOT1_2021_1102), y)

LM_MODEL_DIR_PRE  = lvp/vui/kws/lm_models/enable_lm/mike_bathroom_heater/v0.0.1

INCLUDE_DIR    += $(LM_MODEL_DIR_PRE)/

kws_objs       += $(LM_MODEL_DIR_PRE)/lm_decoder.o
endif
