/* Grus
 * Copyright (C) 1991-2021 Nationalchip Co., Ltd
 *
 * kws_list.h: a Circular Queue using array
 *
 */

#ifndef __KWS_LIST_H__
#define __KWS_LIST_H__

#include <lvp_param.h>

LVP_KWS_PARAM g_kws_param_list[] = {
#ifdef CONFIG_KWS_TYPE_HYBRID

# ifdef CONFIG_KEYWORD_ENABLE_XIAO_AI_TONG_XUE
    {"xiao ai tong xue", {14, 38, 31, 6, 51, 14, 35}, 7, CONFIG_KEYWORD_XIAO_AI_TONG_XUE_THRESHOLD, CONFIG_KEYWORD_XIAO_AI_TONG_XUE_XIP_THRESHOLD, CONFIG_KEYWORD_XIAO_AI_TONG_XUE_VALUE, 1},
# endif
# ifdef CONFIG_KEYWORD_ENABLE_XIAO_DU_XIAO_DU
    {"xiao du xiao du", {14, 38, 5, 22, 14, 38, 5, 22}, 8, CONFIG_KEYWORD_XIAO_DU_XIAO_DU_THRESHOLD, CONFIG_KEYWORD_XIAO_DU_XIAO_DU_XIP_THRESHOLD, CONFIG_KEYWORD_XIAO_DU_XIAO_DU_VALUE, 1},

# if (defined CONFIG_LVP_KWS_GRUS_TWS_ZH_V0DOT2DOT1_2021_0720) || (defined CONFIG_LVP_KWS_GRUS_TWS_ZH_V0DOT2DOT1_V0DOT1DOT9_2021_0722)
    {"#xiao du xiao di", {14, 38, 5, 22, 14, 38, 5, 21}, 8, CONFIG_KEYWORD_XIAO_DU_XIAO_DU_THRESHOLD, CONFIG_KEYWORD_XIAO_DU_XIAO_DU_XIP_THRESHOLD, 200, 1},
    {"#qiao du xiao du", {13, 38, 5, 22, 14, 38, 5, 22}, 8, CONFIG_KEYWORD_XIAO_DU_XIAO_DU_THRESHOLD, CONFIG_KEYWORD_XIAO_DU_XIAO_DU_XIP_THRESHOLD, 200, 1},
    {"#xiao di xiao wu", {14, 38, 5, 21, 14, 38, 19, 22}, 8, CONFIG_KEYWORD_XIAO_DU_XIAO_DU_THRESHOLD, CONFIG_KEYWORD_XIAO_DU_XIAO_DU_XIP_THRESHOLD, 200, 1},
    {"#xiao dao xiao du", {14, 38, 5, 37, 14, 38, 5, 22}, 8, CONFIG_KEYWORD_XIAO_DU_XIAO_DU_THRESHOLD, CONFIG_KEYWORD_XIAO_DU_XIAO_DU_XIP_THRESHOLD, 200, 1},
    {"#xiao du xiao pu", {14, 38, 5, 22, 14, 38, 2, 22}, 8, CONFIG_KEYWORD_XIAO_DU_XIAO_DU_THRESHOLD, CONFIG_KEYWORD_XIAO_DU_XIAO_DU_XIP_THRESHOLD, 200, 1},
    {"#xiao du xiao dai", {14, 38, 5, 22, 14, 38, 5, 31}, 8, CONFIG_KEYWORD_XIAO_DU_XIAO_DU_THRESHOLD, CONFIG_KEYWORD_XIAO_DU_XIAO_DU_XIP_THRESHOLD, 200, 1},
    {"#xiao xai xiao du", {14, 38, 14, 31, 14, 38, 5, 22}, 8, CONFIG_KEYWORD_XIAO_DU_XIAO_DU_THRESHOLD, CONFIG_KEYWORD_XIAO_DU_XIAO_DU_XIP_THRESHOLD, 200, 1},
    {"#xiao di xiao du", {14, 38, 5, 21, 14, 38, 5, 22}, 8, CONFIG_KEYWORD_XIAO_DU_XIAO_DU_THRESHOLD, CONFIG_KEYWORD_XIAO_DU_XIAO_DU_XIP_THRESHOLD, 200, 1},
    // {"#xiao xiao xiao du", {14, 38, 14, 38, 14, 38, 14, 22}, 8, CONFIG_KEYWORD_XIAO_DU_XIAO_DU_THRESHOLD+20, 200, 0},
    // {"xiao du xiao hei", {14, 38, 5, 22, 14, 38, 11, 33}, 8, CONFIG_KEYWORD_XIAO_DU_XIAO_DU_THRESHOLD, 200, 0x80},
    // {"jou li xiao du", {12, 39, 8, 21, 14, 38, 5, 22}, 8, CONFIG_KEYWORD_XIAO_DU_XIAO_DU_THRESHOLD, 200, 0x80},
    // {"xiao du duan du", {14, 38, 5, 22, 14, 38, 5, 22}, 8, CONFIG_KEYWORD_XIAO_DU_XIAO_DU_THRESHOLD, CONFIG_KEYWORD_XIAO_DU_XIAO_DU_VALUE, 0x80},
# endif

# endif
# ifdef CONFIG_KEYWORD_ENABLE_TIAN_MAO_JING_LING
    {"tian mao jing ling", {6, 42, 3, 37, 12, 40, 8, 40}, 8, CONFIG_KEYWORD_TIAN_MAO_JING_LING_THRESHOLD, CONFIG_KEYWORD_TIAN_MAO_JING_LING_XIP_THRESHOLD, CONFIG_KEYWORD_TIAN_MAO_JING_LING_VALUE, 0},
# endif
# ifdef CONFIG_KEYWORD_ENABLE_JIE_TING_DIAN_HUA
    {"jie ting dian hua", {12, 30, 6, 40, 5, 42, 11, 26}, 8, CONFIG_KEYWORD_JIE_TING_DIAN_HUA_THRESHOLD, CONFIG_KEYWORD_JIE_TING_DIAN_HUA_XIP_THRESHOLD, CONFIG_KEYWORD_JIE_TING_DIAN_HUA_VALUE, 0},
# endif
# ifdef CONFIG_KEYWORD_ENABLE_GUA_DIAO_DIAN_HUA
    {"gua diao dian hua", {9, 26, 5, 38, 5, 42, 11, 26}, 8, CONFIG_KEYWORD_GUA_DIAO_DIAN_HUA_THRESHOLD, CONFIG_KEYWORD_GUA_DIAO_DIAN_HUA_XIP_THRESHOLD, CONFIG_KEYWORD_GUA_DIAO_DIAN_HUA_VALUE, 0},
# endif
# ifdef CONFIG_KEYWORD_ENABLE_GUA_DUAN_DIAN_HUA
    {"gua duan dian hua", {9, 26, 5, 43, 5, 42, 11, 26}, 8, CONFIG_KEYWORD_GUA_DUAN_DIAN_HUA_THRESHOLD, CONFIG_KEYWORD_GUA_DUAN_DIAN_HUA_XIP_THRESHOLD, CONFIG_KEYWORD_GUA_DUAN_DIAN_HUA_VALUE, 0},
# endif
# ifdef CONFIG_KEYWORD_ENABLE_JI_XU_BO_FANG
    {"ji xu bo fang", {12, 21, 14, 23, 1, 27, 4, 56}, 8, CONFIG_KEYWORD_JI_XU_BO_FANG_THRESHOLD, CONFIG_KEYWORD_JI_XU_BO_FANG_XIP_THRESHOLD, CONFIG_KEYWORD_JI_XU_BO_FANG_VALUE, 0},
# endif
# ifdef CONFIG_KEYWORD_ENABLE_ZAN_TING_YIN_YUE
    {"zan ting yin yue", {15, 44, 6, 40, 46, 35}, 6, CONFIG_KEYWORD_ZAN_TING_YIN_YUE_THRESHOLD, CONFIG_KEYWORD_ZAN_TING_YIN_YUE_XIP_THRESHOLD, CONFIG_KEYWORD_ZAN_TING_YIN_YUE_VALUE, 0},
# endif
# ifdef CONFIG_KEYWORD_ENABLE_TING_ZHI_YIN_YUE
    {"ting zhi yin yue", {6, 40, 63, 21, 46, 35}, 6, CONFIG_KEYWORD_TING_ZHI_YIN_YUE_THRESHOLD, CONFIG_KEYWORD_TING_ZHI_YIN_YUE_XIP_THRESHOLD, CONFIG_KEYWORD_TING_ZHI_YIN_YUE_VALUE, 0},
# endif
# ifdef CONFIG_KEYWORD_ENABLE_ZAN_TING_BO_FANG
    {"zan ting bo fang", {15, 44, 6, 40, 1, 27, 4, 56}, 8, CONFIG_KEYWORD_ZAN_TING_BO_FANG_THRESHOLD, CONFIG_KEYWORD_ZAN_TING_BO_FANG_XIP_THRESHOLD, CONFIG_KEYWORD_ZAN_TING_BO_FANG_VALUE, 0},
# endif
# ifdef CONFIG_KEYWORD_ENABLE_TING_ZHI_BO_FANG
    {"ting zhi bo fang", {6, 40, 63, 21, 1, 27, 4, 56}, 8, CONFIG_KEYWORD_TING_ZHI_BO_FANG_THRESHOLD, CONFIG_KEYWORD_TING_ZHI_BO_FANG_XIP_THRESHOLD, CONFIG_KEYWORD_TING_ZHI_BO_FANG_VALUE, 0},
# endif
# ifdef CONFIG_KEYWORD_ENABLE_ZENG_DA_YIN_LIANG
    {"zeng da yin liang", {15, 50, 5, 24, 46, 8, 48}, 7, CONFIG_KEYWORD_ZENG_DA_YIN_LIANG_THRESHOLD, CONFIG_KEYWORD_ZENG_DA_YIN_LIANG_XIP_THRESHOLD, CONFIG_KEYWORD_ZENG_DA_YIN_LIANG_VALUE, 0},
# endif
# ifdef CONFIG_KEYWORD_ENABLE_JIAN_XIAO_YIN_LIANG
    {"jian xiao yin liang", {12, 42, 14, 38, 46, 8, 48}, 7, CONFIG_KEYWORD_JIAN_XIAO_YIN_LIANG_THRESHOLD, CONFIG_KEYWORD_JIAN_XIAO_YIN_LIANG_XIP_THRESHOLD, CONFIG_KEYWORD_JIAN_XIAO_YIN_LIANG_VALUE, 0},
# endif
# ifdef CONFIG_KEYWORD_ENABLE_JIA_DA_YIN_LIANG
    {"jia da yin liang", {12, 25, 5, 24, 46, 8, 48}, 7, CONFIG_KEYWORD_JIA_DA_YIN_LIANG_THRESHOLD, CONFIG_KEYWORD_JIA_DA_YIN_LIANG_XIP_THRESHOLD, CONFIG_KEYWORD_JIA_DA_YIN_LIANG_VALUE, 0},
# endif
# ifdef CONFIG_KEYWORD_ENABLE_JIANG_DI_YIN_LIANG
    {"jiang di yin liang", {12, 48, 5, 21, 46, 8, 48}, 7, CONFIG_KEYWORD_JIANG_DI_YIN_LIANG_THRESHOLD, CONFIG_KEYWORD_JIANG_DI_YIN_LIANG_XIP_THRESHOLD, CONFIG_KEYWORD_JIANG_DI_YIN_LIANG_VALUE, 0},
# endif
# ifdef CONFIG_KEYWORD_ENABLE_BO_FANG_YIN_YUE
    {"bo fang yin yue", {1, 27, 4, 56, 46, 35}, 6, CONFIG_KEYWORD_BO_FANG_YIN_YUE_THRESHOLD, CONFIG_KEYWORD_BO_FANG_YIN_YUE_XIP_THRESHOLD, CONFIG_KEYWORD_BO_FANG_YIN_YUE_VALUE, 0},
# endif
# ifdef CONFIG_KEYWORD_ENABLE_SHANG_YI_SHOU
    {"shang yi shou", {60, 56, 20, 21, 60, 39}, 6, CONFIG_KEYWORD_SHANG_YI_SHOU_THRESHOLD, CONFIG_KEYWORD_SHANG_YI_SHOU_XIP_THRESHOLD, CONFIG_KEYWORD_SHANG_YI_SHOU_VALUE, 0x80},
# endif
# ifdef CONFIG_KEYWORD_ENABLE_XIA_YI_SHOU
    {"xia i shou", {14, 25, 21, 60, 39}, 5, CONFIG_KEYWORD_XIA_YI_SHOU_THRESHOLD, CONFIG_KEYWORD_XIA_YI_SHOU_XIP_THRESHOLD, CONFIG_KEYWORD_XIA_YI_SHOU_VALUE, 0x80},
# endif
# ifdef CONFIG_KEYWORD_ENABLE_SHANG_YI_QU
    {"shang yi qu", {60, 56, 20, 21, 13, 23}, 6, CONFIG_KEYWORD_SHANG_YI_QU_THRESHOLD, CONFIG_KEYWORD_SHANG_YI_QU_XIP_THRESHOLD, CONFIG_KEYWORD_SHANG_YI_QU_VALUE, 0x80},
# endif
# ifdef CONFIG_KEYWORD_ENABLE_XIA_YI_QU
    {"xia i qu", {14, 25, 21, 13, 23}, 5, CONFIG_KEYWORD_XIA_YI_QU_THRESHOLD, CONFIG_KEYWORD_XIA_YI_QU_XIP_THRESHOLD, CONFIG_KEYWORD_XIA_YI_QU_VALUE, 0x80},
# endif
# ifdef CONFIG_KEYWORD_ENABLE_DA_KAI_DENG_GUANG
    {"da kai deng guang", {5, 24, 10, 31, 5, 45, 9, 43}, 8, CONFIG_KEYWORD_DA_KAI_DENG_GUANG_THRESHOLD, CONFIG_KEYWORD_DA_KAI_DENG_GUANG_XIP_THRESHOLD, CONFIG_KEYWORD_DA_KAI_DENG_GUANG_VALUE, 0},
# endif
# ifdef CONFIG_KEYWORD_ENABLE_GUAN_BI_DENG_GUNAG
    {"guan bi deng guang", {9, 43, 1,  21, 5, 45, 9, 43}, 8, CONFIG_KEYWORD_GUAN_BI_DENG_GUNAG_THRESHOLD, CONFIG_KEYWORD_GUAN_BI_DENG_GUNAG_XIP_THRESHOLD, CONFIG_KEYWORD_GUAN_BI_DENG_GUNAG_VALUE, 0},
# endif

#else

# ifdef CONFIG_KEYWORD_ENABLE_XIAO_AI_TONG_XUE
    {"xiao ai tong xue", {14, 38, 31, 6, 51, 14, 35}, 7, CONFIG_KEYWORD_XIAO_AI_TONG_XUE_THRESHOLD, CONFIG_KEYWORD_XIAO_AI_TONG_XUE_VALUE, 1},
# endif
# ifdef CONFIG_KEYWORD_ENABLE_XIAO_DU_XIAO_DU
    {"xiao du xiao du", {14, 38, 5, 22, 14, 38, 5, 22}, 8, CONFIG_KEYWORD_XIAO_DU_XIAO_DU_THRESHOLD, CONFIG_KEYWORD_XIAO_DU_XIAO_DU_VALUE, 1},
#  ifdef CONFIG_LVP_KWS_GRUS_TWS_ZH_V0DOT2DOT1_2021_0720
    {"#xiao du xiao di", {14, 38, 5, 22, 14, 38, 5, 21}, 8, CONFIG_KEYWORD_XIAO_DU_XIAO_DU_THRESHOLD, 200, 1},
    {"#qiao du xiao du", {13, 38, 5, 22, 14, 38, 5, 22}, 8, CONFIG_KEYWORD_XIAO_DU_XIAO_DU_THRESHOLD, 200, 1},
    {"#xiao di xiao wu", {14, 38, 5, 21, 14, 38, 19, 22}, 8, CONFIG_KEYWORD_XIAO_DU_XIAO_DU_THRESHOLD, 200, 1},
    {"#xiao dao xiao du", {14, 38, 5, 37, 14, 38, 5, 22}, 8, CONFIG_KEYWORD_XIAO_DU_XIAO_DU_THRESHOLD, 200, 1},
    {"#xiao du xiao pu", {14, 38, 5, 22, 14, 38, 2, 22}, 8, CONFIG_KEYWORD_XIAO_DU_XIAO_DU_THRESHOLD, 200, 1},
    {"#xiao du xiao dai", {14, 38, 5, 22, 14, 38, 5, 31}, 8, CONFIG_KEYWORD_XIAO_DU_XIAO_DU_THRESHOLD, 200, 1},
    {"#xiao xai xiao du", {14, 38, 14, 31, 14, 38, 5, 22}, 8, CONFIG_KEYWORD_XIAO_DU_XIAO_DU_THRESHOLD, 200, 1},
    {"#xiao di xiao du", {14, 38, 5, 21, 14, 38, 5, 22}, 8, CONFIG_KEYWORD_XIAO_DU_XIAO_DU_THRESHOLD, 200, 1},
    // {"#xiao xiao xiao du", {14, 38, 14, 38, 14, 38, 14, 22}, 8, CONFIG_KEYWORD_XIAO_DU_XIAO_DU_THRESHOLD+20, 200, 0},
    // {"xiao du xiao hei", {14, 38, 5, 22, 14, 38, 11, 33}, 8, CONFIG_KEYWORD_XIAO_DU_XIAO_DU_THRESHOLD, 200, 0x80},
    // {"jou li xiao du", {12, 39, 8, 21, 14, 38, 5, 22}, 8, CONFIG_KEYWORD_XIAO_DU_XIAO_DU_THRESHOLD, 200, 0x80},
    // {"xiao du duan du", {14, 38, 5, 22, 14, 38, 5, 22}, 8, CONFIG_KEYWORD_XIAO_DU_XIAO_DU_THRESHOLD, CONFIG_KEYWORD_XIAO_DU_XIAO_DU_VALUE, 0x80},
#  endif
# endif
# ifdef CONFIG_KEYWORD_ENABLE_TIAN_MAO_JING_LING
    {"tian mao jing ling", {6, 42, 3, 37, 12, 40, 8, 40}, 8, CONFIG_KEYWORD_TIAN_MAO_JING_LING_THRESHOLD, CONFIG_KEYWORD_TIAN_MAO_JING_LING_VALUE, 0},
# endif
# ifdef CONFIG_KEYWORD_ENABLE_JIE_TING_DIAN_HUA
    {"jie ting dian hua", {12, 30, 6, 40, 5, 42, 11, 26}, 8, CONFIG_KEYWORD_JIE_TING_DIAN_HUA_THRESHOLD, CONFIG_KEYWORD_JIE_TING_DIAN_HUA_VALUE, 0},
# endif
# ifdef CONFIG_KEYWORD_ENABLE_GUA_DIAO_DIAN_HUA
    {"gua diao dian hua", {9, 26, 5, 38, 5, 42, 11, 26}, 8, CONFIG_KEYWORD_GUA_DIAO_DIAN_HUA_THRESHOLD, CONFIG_KEYWORD_GUA_DIAO_DIAN_HUA_VALUE, 0},
# endif
# ifdef CONFIG_KEYWORD_ENABLE_GUA_DUAN_DIAN_HUA
    {"gua duan dian hua", {9, 26, 5, 43, 5, 42, 11, 26}, 8, CONFIG_KEYWORD_GUA_DUAN_DIAN_HUA_THRESHOLD, CONFIG_KEYWORD_GUA_DUAN_DIAN_HUA_VALUE, 0},
# endif
# ifdef CONFIG_KEYWORD_ENABLE_JI_XU_BO_FANG
    {"ji xu bo fang", {12, 21, 14, 23, 1, 27, 4, 56}, 8, CONFIG_KEYWORD_JI_XU_BO_FANG_THRESHOLD, CONFIG_KEYWORD_JI_XU_BO_FANG_VALUE, 0},
# endif
# ifdef CONFIG_KEYWORD_ENABLE_ZAN_TING_YIN_YUE
    {"zan ting yin yue", {15, 44, 6, 40, 46, 35}, 6, CONFIG_KEYWORD_ZAN_TING_YIN_YUE_THRESHOLD, CONFIG_KEYWORD_ZAN_TING_YIN_YUE_VALUE, 0},
# endif
# ifdef CONFIG_KEYWORD_ENABLE_TING_ZHI_YIN_YUE
    {"ting zhi yin yue", {6, 40, 63, 21, 46, 35}, 6, CONFIG_KEYWORD_TING_ZHI_YIN_YUE_THRESHOLD, CONFIG_KEYWORD_TING_ZHI_YIN_YUE_VALUE, 0},
# endif
# ifdef CONFIG_KEYWORD_ENABLE_ZAN_TING_BO_FANG
    {"zan ting bo fang", {15, 44, 6, 40, 1, 27, 4, 56}, 8, CONFIG_KEYWORD_ZAN_TING_BO_FANG_THRESHOLD, CONFIG_KEYWORD_ZAN_TING_BO_FANG_VALUE, 0},
# endif
# ifdef CONFIG_KEYWORD_ENABLE_TING_ZHI_BO_FANG
    {"ting zhi bo fang", {6, 40, 63, 21, 1, 27, 4, 56}, 8, CONFIG_KEYWORD_TING_ZHI_BO_FANG_THRESHOLD, CONFIG_KEYWORD_TING_ZHI_BO_FANG_VALUE, 0},
# endif
# ifdef CONFIG_KEYWORD_ENABLE_ZENG_DA_YIN_LIANG
    {"zeng da yin liang", {15, 50, 5, 24, 46, 8, 48}, 7, CONFIG_KEYWORD_ZENG_DA_YIN_LIANG_THRESHOLD, CONFIG_KEYWORD_ZENG_DA_YIN_LIANG_VALUE, 0},
# endif
# ifdef CONFIG_KEYWORD_ENABLE_JIAN_XIAO_YIN_LIANG
    {"jian xiao yin liang", {12, 42, 14, 38, 46, 8, 48}, 7, CONFIG_KEYWORD_JIAN_XIAO_YIN_LIANG_THRESHOLD, CONFIG_KEYWORD_JIAN_XIAO_YIN_LIANG_VALUE, 0},
# endif
# ifdef CONFIG_KEYWORD_ENABLE_JIA_DA_YIN_LIANG
    {"jia da yin liang", {12, 25, 5, 24, 46, 8, 48}, 7, CONFIG_KEYWORD_JIA_DA_YIN_LIANG_THRESHOLD, CONFIG_KEYWORD_JIA_DA_YIN_LIANG_VALUE, 0},
# endif
# ifdef CONFIG_KEYWORD_ENABLE_JIANG_DI_YIN_LIANG
    {"jiang di yin liang", {12, 48, 5, 21, 46, 8, 48}, 7, CONFIG_KEYWORD_JIANG_DI_YIN_LIANG_THRESHOLD, CONFIG_KEYWORD_JIANG_DI_YIN_LIANG_VALUE, 0},
# endif
# ifdef CONFIG_KEYWORD_ENABLE_BO_FANG_YIN_YUE
    {"bo fang yin yue", {1, 27, 4, 56, 46, 35}, 6, CONFIG_KEYWORD_BO_FANG_YIN_YUE_THRESHOLD, CONFIG_KEYWORD_BO_FANG_YIN_YUE_VALUE, 0},
# endif
# ifdef CONFIG_KEYWORD_ENABLE_SHANG_YI_SHOU
    {"shang yi shou", {60, 56, 20, 21, 60, 39}, 6, CONFIG_KEYWORD_SHANG_YI_SHOU_THRESHOLD, CONFIG_KEYWORD_SHANG_YI_SHOU_VALUE, 0x80},
# endif
# ifdef CONFIG_KEYWORD_ENABLE_XIA_YI_SHOU
    {"xia i shou", {14, 25, 21, 60, 39}, 5, CONFIG_KEYWORD_XIA_YI_SHOU_THRESHOLD, CONFIG_KEYWORD_XIA_YI_SHOU_VALUE, 0x80},
# endif
# ifdef CONFIG_KEYWORD_ENABLE_SHANG_YI_QU
    {"shang yi qu", {60, 56, 20, 21, 13, 23}, 6, CONFIG_KEYWORD_SHANG_YI_QU_THRESHOLD, CONFIG_KEYWORD_SHANG_YI_QU_VALUE, 0x80},
# endif
# ifdef CONFIG_KEYWORD_ENABLE_XIA_YI_QU
    {"xia i qu", {14, 25, 21, 13, 23}, 5, CONFIG_KEYWORD_XIA_YI_QU_THRESHOLD, CONFIG_KEYWORD_XIA_YI_QU_VALUE, 0x80},
# endif
# ifdef CONFIG_KEYWORD_ENABLE_DA_KAI_DENG_GUANG
    {"da kai deng guang", {5, 24, 10, 31, 5, 45, 9, 43}, 8, CONFIG_KEYWORD_DA_KAI_DENG_GUANG_THRESHOLD, CONFIG_KEYWORD_DA_KAI_DENG_GUANG_VALUE, 0},
# endif
# ifdef CONFIG_KEYWORD_ENABLE_GUAN_BI_DENG_GUNAG
    {"guan bi deng guang", {9, 43, 1,  21, 5, 45, 9, 43}, 8, CONFIG_KEYWORD_GUAN_BI_DENG_GUNAG_THRESHOLD, CONFIG_KEYWORD_GUAN_BI_DENG_GUNAG_VALUE, 0},
# endif

#endif
};

# endif /* __KWS_LIST_H__ */
