#
# Grus
# Copyright (C) 2001-2021 NationalChip Co., Ltd
# ALL RIGHTS RESERVED!
#
# Makefile: 
#
#=================================================================================#

ifeq ($(CONFIG_LVP_LM_MEZIC_HEATING_TABLE_V0DOT0DOT1_2021_0423), y)

LM_MODEL_DIR_PRE  = lvp/vui/kws/lm_models/enable_lm/mezic_heating_table/v0.0.1

INCLUDE_DIR    += $(LM_MODEL_DIR_PRE)/

kws_objs       += $(LM_MODEL_DIR_PRE)/lm_decoder.o
endif
