#
# Grus
# Copyright (C) 2001-2021 NationalChip Co., Ltd
# ALL RIGHTS RESERVED!
#
# Makefile: 
#
#=================================================================================#

ifeq ($(CONFIG_LVP_LM_HELMEL_V0DOT0DOT2_2021_0304), y)

LM_MODEL_DIR_PRE  = lvp/vui/kws/lm_models/enable_lm/helmet/v0.0.2/

INCLUDE_DIR    += $(LM_MODEL_DIR_PRE)/

kws_objs       += $(LM_MODEL_DIR_PRE)/lm_decoder.o
endif
