#
# Grus
# Copyright (C) 2001-2020 NationalChip Co., Ltd
# ALL RIGHTS RESERVED!
#
# Makefile: 
#
#=================================================================================#

ifeq ($(CONFIG_LVP_LM_AUPU_REMOTE_V0DOT0DOT1_2021_0622), y)

LM_MODEL_DIR_PRE  = lvp/vui/kws/lm_models/enable_lm/aupu_remote/v0.0.1/

INCLUDE_DIR    += $(LM_MODEL_DIR_PRE)/

kws_objs       += $(LM_MODEL_DIR_PRE)/lm_decoder.o
endif
