#
# Voice Signal Preprocess
# Copyright (C) 2001-2025 NationalChip Co., Ltd
# ALL RIGHTS RESERVED!
#
# Makefile: source list in dsp/vpa/arach_lib/src/ctc/decoder
#
#=================================================================================#

ifeq ($(CONFIG_LVP_KWS_XIAOSHU_AIOT_VDOT0DOT1DOT0_2025_0427), y)

MODEL_DIR_PRE  = lvp/vui/kws/models/xiaoshu_aiot/v.0.1.0

INCLUDE_DIR    += $(MODEL_DIR_PRE)/
INCLUDE_DIR    += $(MODEL_DIR_PRE)/../
kws_objs       += $(MODEL_DIR_PRE)/ctc_model.o

endif